/* Pilotage Service Technique V46 — moteur d'affichage unique et diagnostic */
(() => {
  'use strict';
  const byId = id => document.getElementById(id);
  let opened = false;
  let lastNotifications = [];
  const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  function computeSafely(){try{const api=window.PSTNotifications;if(!api||typeof api.compute!=='function')return{list:[],error:'Le moteur de notifications n’est pas encore chargé.'};const value=api.compute();return{list:Array.isArray(value)?value:[],error:''}}catch(error){console.error('[Notifications V46] calcul impossible',error);return{list:[],error:error?.message||String(error)}}}
  function diagnosticSummary(){try{return window.PSTDiagnostics?.notificationSummary?.()||null}catch(error){console.error('[Notifications V46] diagnostic impossible',error);return null}}
  function diagnosticHtml(){const d=diagnosticSummary();if(!d)return '<div class="notification-diagnostic"><strong>Diagnostic</strong><span>Données non encore disponibles.</span></div>';const late=(d.maintenanceLateDetails||[]).slice(0,5).map(x=>`<li>${escapeHtml(x.title)} — ${escapeHtml(x.status)} — échéance ${escapeHtml(x.due||'absente')}</li>`).join('');return `<details class="notification-diagnostic"><summary>Diagnostic notifications</summary><div class="diagnostic-grid"><span>Interventions lues <b>${escapeHtml(d.maintenanceTotal)}</b></span><span>Interventions ouvertes <b>${escapeHtml(d.maintenanceOpen)}</b></span><span>Interventions en retard <b>${escapeHtml(d.maintenanceLate)}</b></span><span>Notifications créées <b>${escapeHtml(d.notifications)}</b></span><span>Agents lus <b>${escapeHtml(d.agents)}</b></span><span>Contrôles périodiques <b>${escapeHtml(d.periodicTotal)}</b></span></div>${late?`<ul>${late}</ul>`:'<p>Aucune intervention ouverte en retard détectée.</p>'}<small>Date de calcul : ${escapeHtml(d.today||'')}</small></details>`}
  function render(){const listElement=byId('notificationList'),countElement=byId('notificationCount'),subtitle=byId('notificationSubtitle'),result=computeSafely(),notifications=result.list;lastNotifications=notifications;window.__notifications=notifications;if(countElement){countElement.textContent=String(notifications.length);countElement.classList.toggle('hidden',notifications.length===0)}if(subtitle)subtitle.textContent=result.error?'Erreur de calcul — consulter le diagnostic ci-dessous':notifications.length?`${notifications.length} notification${notifications.length>1?'s':''} à consulter`:'Aucune notification calculée';if(!listElement)return notifications;if(result.error){listElement.innerHTML=`<div class="notification-diagnostic error"><strong>Le calcul a échoué</strong><span>${escapeHtml(result.error)}</span></div>${diagnosticHtml()}`;return notifications}const items=notifications.map((n,index)=>`<button type="button" class="notification-item ${escapeHtml(n.level||'blue')}" data-stable-notification="${index}"><span class="notification-icon">${escapeHtml(n.icon||'🔔')}</span><span><strong>${escapeHtml(n.title||'Notification')}</strong><small>${escapeHtml(n.text||'')}</small></span><span class="go-arrow">›</span></button>`).join('');listElement.innerHTML=items||'<div class="empty-state">✓ Aucune notification à traiter.</div>';listElement.insertAdjacentHTML('beforeend',diagnosticHtml());return notifications}
  function open(event){event?.preventDefault?.();event?.stopPropagation?.();const modal=byId('notificationModal');if(!modal)return;render();modal.classList.remove('hidden');modal.classList.add('is-open');modal.setAttribute('aria-hidden','false');document.body.classList.add('notifications-open');opened=true}
  function close(event){event?.preventDefault?.();event?.stopPropagation?.();const modal=byId('notificationModal');if(!modal)return;modal.classList.remove('is-open');modal.classList.add('hidden');modal.setAttribute('aria-hidden','true');document.body.classList.remove('notifications-open');opened=false}
  function activate(index){const notification=lastNotifications[index];close();if(!notification)return;try{window.PSTNotifications?.target?.(notification)}catch(error){console.error('[Notifications V46] navigation impossible',error)}}
  function init(){const bell=byId('notificationBell'),closeButton=byId('notificationClose'),backdrop=byId('notificationBackdrop');if(bell){bell.removeAttribute('href');bell.setAttribute('role','button');bell.setAttribute('tabindex','0');bell.addEventListener('click',open,{passive:false});bell.addEventListener('touchend',open,{passive:false});bell.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' ')open(event)})}closeButton?.addEventListener('click',close);backdrop?.addEventListener('click',close);document.addEventListener('click',event=>{const button=event.target.closest('[data-stable-notification]');if(button)activate(Number(button.dataset.stableNotification))});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&opened)close(event)});['pst:data-loaded','pst:data-saved','online'].forEach(name=>window.addEventListener(name,render));render();setTimeout(render,1000);setTimeout(render,3500);setTimeout(render,10000);setInterval(render,60000)}
  window.PSTNotificationCenter={open,close,render,diagnosticSummary};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
