/* Pilotage Service Technique V50 — cartes mobiles, masquage et détails */
(() => {
 'use strict';
 const byId=id=>document.getElementById(id);let opened=false,lastNotifications=[];
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const key=n=>n.type==='cleaning-summary'?[n.type||'',n.id||'',n.title||'',...(n.details||[])].join('|'):[n.type||'',n.id||'',n.date||'',n.title||'',n.text||''].join('|');
 const mainDb=()=>window.PSTMainState?.get?.()||null;
 const load=()=>{const d=mainDb();return d&&d.notificationDismissals&&typeof d.notificationDismissals==='object'?d.notificationDismissals:{}};
 const save=x=>{const d=mainDb();if(!d)return false;d.notificationDismissals=x||{};window.PSTMainState?.save?.(false);return true};
 function prune(store){const now=Date.now();for(const [k,v] of Object.entries(store))if(!v||Number(v)<=now)delete store[k];return store}
 function compute(){try{const raw=window.PSTNotifications?.compute?.()||[],before=load(),beforeCount=Object.keys(before).length,store=prune(before);if(Object.keys(store).length!==beforeCount)save(store);return{all:Array.isArray(raw)?raw:[],list:(Array.isArray(raw)?raw:[]).filter(n=>!store[key(n)]),error:''}}catch(e){return{all:[],list:[],error:e?.message||String(e)}}}
 function diagnostic(){try{return window.PSTDiagnostics?.notificationSummary?.()||null}catch{return null}}
 function diagnosticHtml(){const d=diagnostic();if(!d)return'';return `<details class="notification-diagnostic"><summary>Diagnostic notifications</summary><div class="diagnostic-grid"><span>Interventions lues <b>${esc(d.maintenanceTotal)}</b></span><span>Interventions en retard <b>${esc(d.maintenanceLate)}</b></span><span>Notifications calculées <b>${esc(d.notifications)}</b></span><span>Agents lus <b>${esc(d.agents)}</b></span></div></details>`}
 function render(){const result=compute(),list=result.list;lastNotifications=list;window.__notifications=list;const count=byId('notificationCount'),subtitle=byId('notificationSubtitle'),box=byId('notificationList');if(count){count.textContent=String(list.length);count.classList.toggle('hidden',!list.length)}if(subtitle)subtitle.textContent=result.error?'Erreur de calcul':list.length?`${list.length} notification${list.length>1?'s':''} à consulter`:'Aucune notification visible';if(!box)return list;
  const toolbar=`<div class="notification-toolbar"><button type="button" data-dismiss-all>Effacer les notifications affichées</button><button type="button" data-restore-dismissed>Réafficher les masquées</button></div>`;
  const items=list.map((n,i)=>{const detail=Array.isArray(n.details)&&n.details.length?`<div class="notification-detail hidden" id="notification-detail-${i}"><strong>Détail</strong><ul>${n.details.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:'';const detailButton=detail?`<button type="button" class="notification-detail-toggle" data-toggle-notification-detail="${i}" aria-expanded="false">Voir le détail</button>`:'';const actions=n.type==='cleaning-summary'?`<div class="cleaning-notification-actions"><button type="button" data-clean-action="treated" data-index="${i}">✓ Tout traiter</button><button type="button" data-clean-action="24h" data-index="${i}">Masquer 24 h</button><button type="button" data-clean-action="tomorrow" data-index="${i}">Demain</button><button type="button" data-clean-action="7d" data-index="${i}">7 jours</button><button type="button" data-clean-action="30d" data-index="${i}">30 jours</button><button type="button" class="danger-mini" data-clean-action="delete" data-index="${i}">Tout supprimer</button></div>`:'';return `<article class="notification-item ${esc(n.level||'blue')}"><div class="notification-card-row"><button type="button" class="notification-main" data-open-notification="${i}"><span class="notification-icon">${esc(n.icon||'🔔')}</span><span class="notification-content"><strong>${esc(n.title||'Notification')}</strong><small>${esc(n.text||'')}</small>${detailButton}</span><span class="go-arrow">›</span></button><button type="button" class="notification-dismiss" data-dismiss-notification="${i}" aria-label="Masquer cette notification" title="Masquer">×</button></div>${detail}${actions}</article>`}).join('');
  box.innerHTML=toolbar+(items||'<div class="empty-state">✓ Aucune notification à traiter.</div>')+diagnosticHtml();return list}
 function dismiss(index,days=7){const n=lastNotifications[index];if(!n)return;const store=load();store[key(n)]=Date.now()+days*86400000;save(store);render()}
 function dismissAll(){const store=load(),until=Date.now()+86400000;for(const n of lastNotifications)store[key(n)]=until;save(store);render()}
 function restore(){save({});render()}
 function open(e){e?.preventDefault?.();e?.stopPropagation?.();const m=byId('notificationModal');if(!m)return;render();m.classList.remove('hidden');m.classList.add('is-open');m.setAttribute('aria-hidden','false');document.body.classList.add('notifications-open');opened=true}
 function close(e){e?.preventDefault?.();const m=byId('notificationModal');if(!m)return;m.classList.remove('is-open');m.classList.add('hidden');m.setAttribute('aria-hidden','true');document.body.classList.remove('notifications-open');opened=false}
 function activate(i){const n=lastNotifications[i];close();if(n)window.PSTNotifications?.target?.(n)}
 function toggleDetail(index,button){const detail=byId(`notification-detail-${index}`);if(!detail)return;const willOpen=detail.classList.contains('hidden');detail.classList.toggle('hidden',!willOpen);button?.setAttribute('aria-expanded',String(willOpen));if(button)button.textContent=willOpen?'Masquer le détail':'Voir le détail'}

 function cleanAction(index,action){const n=lastNotifications[index];if(!n)return;const store=load();let until=0;if(action==='24h'||action==='tomorrow')until=Date.now()+86400000;else if(action==='7d')until=Date.now()+7*86400000;else if(action==='30d')until=Date.now()+30*86400000;else if(action==='treated'||action==='delete')until=new Date('2100-01-01T00:00:00').getTime();if(until){store[key(n)]=until;save(store);render()}}
 function init(){const bell=byId('notificationBell');if(bell){bell.removeAttribute('href');bell.addEventListener('click',open,{passive:false});bell.addEventListener('touchend',open,{passive:false})}byId('notificationClose')?.addEventListener('click',close);byId('notificationBackdrop')?.addEventListener('click',close);document.addEventListener('click',e=>{let x=e.target.closest('[data-toggle-notification-detail]');if(x){e.preventDefault();e.stopPropagation();return toggleDetail(Number(x.dataset.toggleNotificationDetail),x)}x=e.target.closest('[data-open-notification]');if(x)return activate(Number(x.dataset.openNotification));x=e.target.closest('[data-dismiss-notification]');if(x)return dismiss(Number(x.dataset.dismissNotification));if(e.target.closest('[data-dismiss-all]'))return dismissAll();if(e.target.closest('[data-restore-dismissed]'))return restore();x=e.target.closest('[data-clean-action]');if(x){e.preventDefault();e.stopPropagation();return cleanAction(Number(x.dataset.index),x.dataset.cleanAction)}});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&opened)close(e)});['pst:data-loaded','pst:data-saved','online'].forEach(n=>window.addEventListener(n,render));render();setInterval(render,60000)}
 window.PSTNotificationCenter={open,close,render,restore};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
