(()=>{'use strict';
const KEY='pst_room_preps_v106',PRONOTE_KEY='pst_pronote_url_v106';const $=id=>document.getElementById(id),uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);let editingId='';
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY))||[]}catch{return[]}}, saveList=v=>{localStorage.setItem(KEY,JSON.stringify(v));render()}, esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}, fmtDate=v=>v?new Date(`${v}T12:00:00`).toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long',year:'numeric'}):'';
const ref=()=>window.PSTCleaningRooms?.get?.()||[], roomLabel=r=>[r?.number||'',r?.name||''].filter(Boolean).join(' — ')||r?.type||'Local';
function fillB(sel={}){const d=ref(),e=$('rpBuilding');if(!e)return;e.innerHTML=d.map((x,i)=>`<option value="${i}">${esc(x.name)}</option>`).join('');e.value=String(sel.building??0);fillF(sel)}
function fillF(sel={}){const d=ref(),bi=+$('rpBuilding').value,e=$('rpFloor'),a=d[bi]?.floors||[];e.innerHTML=a.map((x,i)=>`<option value="${i}">${esc(x.name)}</option>`).join('');e.value=String(sel.floor??0);fillS(sel)}
function fillS(sel={}){const d=ref(),bi=+$('rpBuilding').value,fi=+$('rpFloor').value,e=$('rpSector'),a=d[bi]?.floors[fi]?.sectors||[];e.innerHTML=a.map((x,i)=>`<option value="${i}">${esc(x.name)}</option>`).join('');e.value=String(sel.sector??0);fillR(sel)}
function fillR(sel={}){const d=ref(),bi=+$('rpBuilding').value,fi=+$('rpFloor').value,si=+$('rpSector').value,e=$('rpRoom'),a=d[bi]?.floors[fi]?.sectors[si]?.rooms||[];e.innerHTML=a.map((x,i)=>`<option value="${i}">${esc(roomLabel(x))}</option>`).join('')+'<option value="other">Autre lieu…</option>';e.value=String(sel.room??0);toggleOther()}
function toggleOther(){$('rpOtherLocationWrap')?.classList.toggle('hidden',$('rpRoom')?.value!=='other')}
function loc(){const d=ref(),bi=+$('rpBuilding').value,fi=+$('rpFloor').value,si=+$('rpSector').value,rv=$('rpRoom').value,b=d[bi],f=b?.floors[fi],s=f?.sectors[si];if(rv==='other')return{building:b?.name||'',floor:f?.name||'',sector:s?.name||'',room:$('rpOtherLocation').value.trim()||'Autre lieu',roomId:'',other:true};const r=s?.rooms?.[+rv];return{building:b?.name||'',floor:f?.name||'',sector:s?.name||'',room:roomLabel(r),roomId:r?.id||'',other:false}}
function data(){const l=loc();return{id:editingId||uid(),date:$('rpDate').value,time:$('rpTime').value,...l,requester:$('rpRequester').value.trim(),people:+$('rpPeople').value||0,owner:$('rpOwner').value.trim(),status:$('rpStatus').value,deadlineTime:$('rpDeadlineTime').value,layout:$('rpLayout').value,tables:+$('rpTables').value||0,chairs:+$('rpChairs').value||0,partition:$('rpPartition').value,otherPrep:$('rpOtherPrep').value,otherPrepComment:$('rpOtherPrepComment').value.trim(),roomSetup:{projector:!!$('rpProjector').checked,screen:!!$('rpScreen').checked,mic:!!$('rpMic').checked,extension:!!$('rpExtension').checked,tablecloth:!!$('rpTablecloth').checked,bins:!!$('rpBins').checked,signage:!!$('rpSignage').checked,pmr:!!$('rpPMR').checked},coffee:{enabled:$('rpCoffee').value==='Oui',people:+$('rpCoffeePeople').value||0,time:$('rpCoffeeTime').value,comment:$('rpCoffeeComment').value.trim()},notes:$('rpNotes').value.trim(),updatedAt:new Date().toISOString()}}
function reset(){editingId='';$('rpDate').value=today();$('rpTime').value='';$('rpRequester').value='';$('rpPeople').value=10;$('rpOwner').value='';$('rpStatus').value='À préparer';$('rpDeadlineTime').value='';$('rpLayout').value='Réunion';$('rpTables').value=0;$('rpChairs').value=0;$('rpPartition').value='Non';$('rpOtherPrep').value='Non';$('rpOtherPrepComment').value='';$('rpOtherPrepCommentWrap').classList.add('hidden');$('rpCoffee').value='Non';$('rpCoffeePeople').value=0;$('rpCoffeeTime').value='';$('rpCoffeeComment').value='';$('rpNotes').value='';['rpProjector','rpScreen','rpMic','rpExtension','rpTablecloth','rpBins','rpSignage','rpPMR'].forEach(id=>$(id).checked=false);fillB()}
function save(){const v=data();if(!v.date||!v.room)return alert('Renseignez la date et le lieu.');let a=load(),i=a.findIndex(x=>x.id===v.id);if(i>=0)a[i]=v;else a.push(v);a.sort((x,y)=>`${x.date}T${x.time||'00:00'}`.localeCompare(`${y.date}T${y.time||'00:00'}`));saveList(a);reset();alert('Préparation enregistrée et ajoutée à Agenda personnel.')}
function summary(v){return [`${v.tables||0} table(s)`,`${v.chairs||0} chaise(s)`,v.partition==='Oui'?'Cloison ouverte':'',v.coffee?.enabled?`Café ${v.coffee.people||v.people||0} pers.`:''].filter(Boolean).join(' · ')}
function render(){const now=today(),a=load().filter(x=>x.date>=now&&x.status!=='Terminé'),list=$('roomPrepList'),ag=$('roomPrepAgenda');if(list)list.innerHTML=a.length?a.map(v=>`<article class="roomprep-card"><div class="roomprep-card-head"><div><strong>${esc(fmtDate(v.date))}${v.time?` · ${esc(v.time)}`:''}</strong><h4>${esc(v.room)}</h4><small>${esc(v.building||'')} ${v.floor?`· ${esc(v.floor)}`:''}</small></div><span class="badge">${esc(v.status)}</span></div><p>${v.people} personne(s)</p><small>${esc(summary(v))}</small></article>`).join(''):'<div class="empty">Aucune préparation à venir.</div>';if(ag)ag.innerHTML=a.length?a.slice(0,12).map(v=>`<button class="roomprep-agenda-item"><span>${esc(v.date)}${v.time?` · ${esc(v.time)}`:''}</span><strong>${esc(v.room)} — ${v.people} pers.</strong><small>${esc(v.status)}${v.coffee?.enabled?' · ☕ Café':''}</small></button>`).join(''):'<div class="empty">Aucune préparation à venir.</div>'}
function openPrep(){document.querySelector('.nav-btn[data-view="room-prep"]')?.click();setTimeout(()=>$('roomPrepEditorPanel')?.scrollIntoView({behavior:'smooth'}),50)}
function pronote(){window.open((localStorage.getItem(PRONOTE_KEY)||'').trim()||'https://www.index-education.com/fr/','_blank','noopener')}
function init(){
 $('rpOtherPrep')?.addEventListener('change',()=>$('rpOtherPrepCommentWrap')?.classList.toggle('hidden',$('rpOtherPrep').value!=='Oui'));
reset();render();$('rpBuilding')?.addEventListener('change',()=>fillF());$('rpFloor')?.addEventListener('change',()=>fillS());$('rpSector')?.addEventListener('change',()=>fillR());$('rpRoom')?.addEventListener('change',toggleOther);$('rpOtherPrep')?.addEventListener('change',()=>$('rpOtherPrepCommentWrap').classList.toggle('hidden',$('rpOtherPrep').value!=='Oui'));document.querySelectorAll('[data-quick-roomprep]').forEach(x=>x.addEventListener('click',openPrep));$('openRoomPrepFromAgenda')?.addEventListener('click',openPrep);$('roomPrepPronote')?.addEventListener('click',pronote);$('roomPrepSave')?.addEventListener('click',save);$('roomPrepReset')?.addEventListener('click',reset)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();window.PSTRoomPrep={render,load,pronote};})();